# The name of the action
name: Django Automatic Tests
# When the action is triggered
on:
  pull_request:
    branches:
      - master

      # What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  build:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

        # Install Python 3.8
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Run django tests
      - name: Test with pytest
        run: poetry run pytest -vv
